version: '3.8'

services:
  # MongoDB para servicio de viajes
  mongodb:
    image: mongo:6.0
    container_name: mongo_rides
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rides_db
    volumes:
      - mongo_data:/data/db

  # MySQL para servicio de usuarios
  mysql_user:
    image: mysql:8.0
    container_name: mysql_user
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: user_db
    volumes:
      - mysql_user_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # MySQL para servicio de transporte
  mysql_transport:
    image: mysql:8.0
    container_name: mysql_transport
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: transport_db
    volumes:
      - mysql_transport_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # MySQL para servicio de mantenimiento
  mysql_maintenance:
    image: mysql:8.0
    container_name: mysql_maintenance
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: maintenance_db
    volumes:
      - mysql_maintenance_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mongo_data:
  mysql_user_data:
  mysql_transport_data:
  mysql_maintenance_data:
